'use strict';
(() => {
const URL_BASE='https://txpdbljehqkntdxrpoof.supabase.co';
const PUBLIC_KEY='sb_publishable_ug2_CfqwXNVUoWaVtq-KQA_W7BtaTcS';
const TZ='Asia/Jerusalem', A=MOOD_ASSETS, $=id=>document.getElementById(id);
const CATS={all:['הכל','✦','romantic'],romantic:['רומנטי','♡','romantic'],relax:['מנוחה','☁','relax'],party:['מסיבות','◉','party'],clubs:['מועדונים','♫','party'],bars:['ברים','♧','food'],music:['הופעות','♪','music'],nature:['טבע וטיולים','↟','nature'],family:['משפחה','☀','family'],kids:['ילדים','☆','family'],food:['קולינריה','♨','food'],hotel:['מלונות','▤','relax'],spa:['ספא','❋','relax'],culture:['תרבות','◇','music'],comedy:['סטנדאפ','☺','music'],extreme:['אקסטרים','↗','nature'],sports:['ספורט','◎','nature']};
const txt=v=>{const d=new DOMParser().parseFromString(String(v??''),'text/html');return (d.body.textContent||'').replace(/\s+/g,' ').trim();};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>{try{const u=new URL(String(v));return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}};
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)??'null')??f;}catch{return f;}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true;}catch{return false;}};
const date=v=>{if(!v)return null;const d=new Date(v);return Number.isFinite(d.getTime())?d:null;};
const day=v=>{const d=v?new Date(v):new Date();const p=new Intl.DateTimeFormat('en-GB',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d);const g=t=>p.find(x=>x.type===t).value;return `${g('year')}-${g('month')}-${g('day')}`;};
const plus=(d,n)=>{const t=new Date(d+'T12:00:00Z');t.setUTCDate(t.getUTCDate()+n);return t.toISOString().slice(0,10);};
const at=(d,h=0)=>{const [y,m,x]=d.split('-').map(Number),want=Date.UTC(y,m-1,x,h);let g=want;for(let i=0;i<3;i++){const p=new Intl.DateTimeFormat('en-GB',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(g);const k=t=>+p.find(q=>q.type===t).value;const actual=Date.UTC(k('year'),k('month')-1,k('day'),k('hour'),k('minute'),k('second'));g+=want-actual;}return g;};
const dlabel=v=>new Intl.DateTimeFormat('he-IL',{timeZone:TZ,day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v));
const clock=v=>new Intl.DateTimeFormat('he-IL',{timeZone:TZ,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(v));
const num=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(+v)&&+v>=0?+v:null;
const currency=(p,c='ILS')=>new Intl.NumberFormat('he-IL',{style:'currency',currency:/^[A-Z]{3}$/.test(c)?c:'ILS',maximumFractionDigits:2}).format(p);
const defaults=()=>({mood:'all',region:'all',city:'',from:day(),to:plus(day(),7),age:null,budget:null,known:false});
const list=v=>Array.isArray(v)?v:[];
const oldSaved=[...list(read('mt_saved',[])),...list(read('mta_saved',[])),...list(read('mta_v8_saved',[]))].filter(x=>typeof x==='string');
const s={rows:[],byId:new Map(),saved:new Set(oldSaved),filters:defaults(),view:'home',query:'',sort:'date',limit:18,nightKind:'all',plan:read('mta_v8_plan',null),mode:'loading',stats:null,loading:false,formMode:'search',detailId:null,hidden:0};
let toastTimer;
function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,2400);}
function category(a){const c=a.category||'';if(a.type==='hotel'||/מלונ|מלון/.test(c))return 'hotel';if(/ספא/.test(c))return 'spa';if(/סטנד.?אפ|קומדי/.test(c))return 'comedy';if(/מועדו|מסיב/.test(c))return 'party';if(/ברים|^בר |בר ומוזיקה/.test(c))return 'bars';if(/הופע|קונצרט|מוזיקה/.test(c))return 'music';if(/טבע|טיול/.test(c))return 'nature';if(/אוכל|קולינר|מסעד|יין/.test(c))return 'food';if(/אקסטרים/.test(c))return 'extreme';if(/אטרקצי|שעשוע|מדע|אקווריו/.test(c))return 'family';return (a.moods||[]).find(x=>CATS[x]&&x!=='all')||'culture';}
function normalize(input){const out=[],seen=new Map();for(const r of input){if(!r||typeof r!=='object')continue;const a={...r};a.title=txt(a.title);a.description=txt(a.description);a.category=txt(a.category);a.city=txt(a.city);a.venue=txt(a.venue);a.source_name=txt(a.source_name);a.moods=Array.isArray(a.moods)?a.moods.filter(x=>CATS[x]):[];a.region=txt(a.region)||'כל הארץ';a.id=String(a.id||'');a.source_url=safe(a.source_url);a.booking_url=safe(a.booking_url)||a.source_url;a.image_url=safe(a.image_url);a.starts_at=date(a.starts_at)?.toISOString()||null;a.ends_at=date(a.ends_at)?.toISOString()||null;a.price_from=num(a.price_from);a.min_age=num(a.min_age);a.max_age=num(a.max_age);a.currency=/^[A-Z]{3}$/.test(a.currency)?a.currency:'ILS';a.cat=category(a);a.kind=a.cat==='hotel'?'hotel':a.type==='venue'?'venue':['attraction','restaurant'].includes(a.type)?'place':'event';a.isFree=a.is_free===true&&(a.price_from===0||/חינם|ללא עלות|כניסה חופשית/.test(a.description));if(a.isFree)a.price_from=0;if(!a.isFree&&a.price_from===0)a.price_from=null;
 if(!a.id||a.title.length<3||!a.booking_url||/^(לפרטים נוספים|קרא עוד|מידע נוסף|הזמנה|רכישת כרטיסים|לכל האירועים|קנו עכשיו|read more)$/i.test(a.title))continue;
 const start=a.starts_at?+new Date(a.starts_at):null,end=a.ends_at?+new Date(a.ends_at):null;
 a.timeUnclear=!!(a.kind==='event'&&start&&end&&(end<start||end-start>18*3600000));
 a.endEffective=end&&!a.timeUnclear?end:null;
 const expired=start&&(a.kind==='hotel'?(end?end<=Date.now():day(start)<day()):a.endEffective?a.endEffective<=Date.now():day(start)<day());
 if(expired)continue;
 if(a.image_url===a.source_url||a.image_url===a.booking_url||/\.(?:html?|php)(?:\?|$)/i.test(a.image_url)||/^https?:\/\/[^/]+\/?$/.test(a.image_url))a.image_url='';
 const key=[a.title.toLowerCase().replace(/[^\p{L}\p{N}]/gu,''),a.city||a.venue,a.starts_at?day(a.starts_at):'',a.ends_at?day(a.ends_at):''].join('|');
 if(seen.has(key)){const old=seen.get(key);if(!old.image_url&&a.image_url)old.image_url=a.image_url;if(old.price_from===null&&a.price_from!==null){old.price_from=a.price_from;old.currency=a.currency;old.isFree=a.isFree;}continue;}seen.set(key,a);out.push(a);
 }return out;}
function imageKey(a){if(a.cat==='party'||a.cat==='clubs')return 'party';if(a.cat==='hotel'||a.cat==='spa'||a.cat==='relax')return 'relax';if(['family','kids'].includes(a.cat))return 'family';if(['nature','extreme','sports'].includes(a.cat))return 'nature';if(a.cat==='food'||a.cat==='bars')return 'food';if(['music','culture','comedy'].includes(a.cat))return 'music';return 'romantic';}
function image(a,cls='offer-media'){const k=imageKey(a);return `<div class="${cls}"><img src="${esc(A[k])}" alt="${esc('תמונת אווירה — '+CATS[a.cat]?.[0])}" loading="lazy" decoding="async" data-fallback="${k}" data-illustration="1"${a.image_url?' data-source="'+esc(a.image_url)+'" data-title="'+esc(a.title)+'"':''}><small class="image-note">תמונת אווירה</small></div>`;}
// Keep the embedded image visible until a provider image has really loaded.
const imageCache=new Map();
function upgradeImage(im){const url=im.dataset.source;if(!url)return;delete im.dataset.source;if(imageCache.get(url)===false)return;const apply=()=>{if(!im.isConnected)return;im.src=url;im.alt=im.dataset.title||'תמונה מהמקור';delete im.dataset.illustration;const note=im.parentElement.querySelector('.image-note');if(note)note.textContent='תמונה מהמקור';};if(imageCache.get(url)===true){apply();return;}const probe=new Image();let done=false;const timeout=setTimeout(()=>{done=true;probe.onload=null;probe.onerror=null;},7000);probe.onload=()=>{clearTimeout(timeout);if(done)return;done=true;imageCache.set(url,true);if(probe.naturalWidth>1&&probe.naturalHeight>1)apply();};probe.onerror=()=>{clearTimeout(timeout);done=true;imageCache.set(url,false);};probe.src=url;}
const imageObserver='IntersectionObserver' in window?new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){imageObserver.unobserve(e.target);upgradeImage(e.target);}}),{rootMargin:'180px'}):null;
function hydrateImages(){document.querySelectorAll('img[data-source]').forEach(im=>imageObserver?imageObserver.observe(im):upgradeImage(im));}
const kindLabel=a=>a.kind==='hotel'?'לינה ונופש':a.kind==='venue'?'מקום לבילוי':a.starts_at?'אירוע מתוארך':'בדיקת מועד';
const priceLabel=a=>a.isFree?'חינם':a.price_from===null?'מחיר לא פורסם':'מ־'+currency(a.price_from,a.currency);
function dateLabel(a){if(!a.starts_at)return 'מועד וזמינות בבדיקה אצל הספק';if(a.kind==='hotel')return `${dlabel(a.starts_at)}${a.ends_at?' – '+dlabel(a.ends_at):''} · תאריכי ההצעה`;return `${dlabel(a.starts_at)} · ${clock(a.starts_at)}${a.timeUnclear?' · שעות טעונות בדיקה':''}`;}
const host=u=>{try{return new URL(u).hostname.replace(/^www\./,'');}catch{return '';}};
function card(a){return `<article class="offer-card" data-card="${esc(a.id)}"><div style="position:relative">${image(a)}<span class="kind-label">${esc(CATS[a.cat]?.[0]||a.category)}</span><button class="save-btn" data-save="${esc(a.id)}" aria-label="שמירת ${esc(a.title)}" aria-pressed="${s.saved.has(a.id)}">${s.saved.has(a.id)?'♥':'♡'}</button></div><div class="offer-content"><div class="place-line">⌖ ${esc(a.city||a.venue||a.region)}</div><h3>${esc(a.title)}</h3><div class="date-line">${esc(dateLabel(a))}</div><p class="offer-desc">${esc(a.description.slice(0,180))}</p><div class="offer-bottom"><span class="price ${a.price_from===null?'unknown':''}">${esc(priceLabel(a))}</span><button class="details-btn" data-detail="${esc(a.id)}">לפרטים ולהזמנה ↗</button></div><small class="source-line">מקור: ${esc(a.source_name||host(a.source_url))}</small></div></article>`;}
function empty(title,message,action='filters'){return `<div class="empty"><h3>${esc(title)}</h3><p>${esc(message)}</p>${action?`<button class="secondary" data-action="${action}">${action==='refresh'?'ניסיון נוסף':'שינוי המסננים'}</button>`:''}</div>`;}
function loadEmpty(){return empty('טוען את ההצעות…','החיבור למאגר מתבצע עכשיו.','');}
function moodMatch(a,m){if(m==='all')return true;if(m==='hotel')return a.kind==='hotel';if(m==='spa')return a.cat==='spa'||/ספא/.test(a.title);if(m==='bars')return a.cat==='bars';if(m==='clubs')return a.cat==='party'||a.kind==='venue'&&a.moods.includes('clubs');if(m==='party')return a.cat==='party';if(m==='music')return a.cat==='music'||a.cat==='party'&&a.moods.includes('music');return a.cat===m||a.moods.includes(m);}
function basic(a,f){if(f.region!=='all'&&a.region!==f.region)return false;if(f.city&&a.city!==f.city)return false;if(f.age!==null&&((a.min_age!==null&&f.age<a.min_age)||(a.max_age!==null&&f.age>a.max_age)))return false;if(f.known&&a.price_from===null)return false;if(f.budget===0&&!a.isFree)return false;if(f.budget!==null&&a.price_from!==null&&(a.currency!=='ILS'||a.price_from>f.budget))return false;return true;}
function inRange(a,f){if(!a.starts_at)return true;const start=+new Date(a.starts_at),lo=at(f.from),hi=at(plus(f.to,1));if(a.kind==='hotel'&&a.ends_at)return +new Date(a.ends_at)>lo&&start<hi;return start>=lo&&start<hi;}
function sorted(rows){return [...rows].sort((a,b)=>s.sort==='name'?a.title.localeCompare(b.title,'he'):s.sort==='price'?((a.currency==='ILS'?a.price_from:null)??Infinity)-((b.currency==='ILS'?b.price_from:null)??Infinity):((a.starts_at?+new Date(a.starts_at):Infinity)-(b.starts_at?+new Date(b.starts_at):Infinity))||a.title.localeCompare(b.title,'he'));}
function results(){const q=s.query.toLocaleLowerCase();return sorted(s.rows.filter(a=>basic(a,s.filters)&&moodMatch(a,s.filters.mood)&&inRange(a,s.filters)&&(!q||[a.title,a.description,a.city,a.venue].join(' ').toLocaleLowerCase().includes(q))));}
function closeDialogs(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());}
function view(v,history=true){if(!['home','explore','night','plan','saved'].includes(v))return;closeDialogs();s.view=v;document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!=='view-'+v);document.querySelectorAll('.bottom [data-view]').forEach(b=>{if(b.dataset.view===v)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(history&&location.hash!=='#'+v)window.history.pushState({view:v},'', '#'+v);render();window.scrollTo({top:0,behavior:'instant'});}
function renderHome(){const f={...s.filters,from:day(),to:plus(day(),60),mood:'all'};const pool=s.rows.filter(a=>basic(a,f)&&inRange(a,f));const chosen=[];for(const k of ['party','music','hotel','nature','family','food','spa','culture']){const a=sorted(pool).find(x=>moodMatch(x,k)&&!chosen.includes(x));if(a)chosen.push(a);}for(const a of sorted(pool)){if(chosen.length>=8)break;if(!chosen.includes(a))chosen.push(a);}$('homeCards').innerHTML=chosen.length?chosen.map(card).join(''):s.mode==='loading'?loadEmpty():empty('אין כרגע הצעות להצגה','נסו רענון או הרחבת האזור.','refresh');}
function renderExplore(){const rows=results();$('filterSummary').innerHTML=`<button class="chip" data-action="filters">${esc(CATS[s.filters.mood][0])} · ${esc(s.filters.region==='all'?'כל הארץ':s.filters.region)}${s.filters.city?' · '+esc(s.filters.city):''}</button><button class="chip" data-action="filters">${esc(dlabel(at(s.filters.from))+' – '+dlabel(at(s.filters.to)))}</button>`;$('resultCount').textContent=`${rows.length} תוצאות אחרי סינון`;$('exploreCards').innerHTML=rows.length?rows.slice(0,s.limit).map(card).join(''):s.mode==='loading'?loadEmpty():empty('עוד לא מצאנו התאמה','אין כרגע תוצאות למסננים האלה. הרחיבו תאריכים או בחרו סגנון אחר.');$('moreButton').hidden=rows.length<=s.limit;hydrateImages();}
function isNight(a){return a.kind!=='hotel'&&['party','music','bars','comedy'].includes(a.cat);}
function renderNight(){const target=$('nightDate').value||day(),lo=at(target,17),hi=at(plus(target,1),6);const matches=a=>basic(a,s.filters)&&isNight(a)&&(s.nightKind==='all'||moodMatch(a,s.nightKind));const events=sorted(s.rows.filter(a=>{if(!matches(a)||a.kind!=='event'||!a.starts_at)return false;const start=+new Date(a.starts_at);return start>=lo&&start<hi||start<lo&&a.endEffective&&a.endEffective>lo;}));const venues=s.rows.filter(a=>matches(a)&&!a.starts_at);$('nightSummary').textContent=`${events.length} אירועים עם מועד במאגר · ${dlabel(lo)} · ${s.filters.region==='all'?'כל הארץ':s.filters.region}`;$('nightCards').innerHTML=events.length?events.map(card).join(''):s.mode==='loading'?loadEmpty():empty('אין אירועים מתוארכים ללילה הזה','זה לא אומר שאין בילויים באזור. בדקו תאריך אחר או את מקומות הבילוי בהמשך.');$('venueCards').innerHTML=venues.length?venues.slice(0,12).map(card).join(''):empty('אין מקומות נוספים במסנן הזה','אפשר לחפש במאגר המלא.','');hydrateImages();}
function renderSaved(){const rows=s.rows.filter(a=>s.saved.has(a.id));$('savedCards').innerHTML=rows.length?rows.map(card).join(''):empty('כל החוויות שלכם, במקום אחד','לחצו על הלב בכרטיס כדי לשמור. פריטים שפגו או הוסרו מהמאגר לא מוצגים.','');hydrateImages();}
function render(){if(s.view==='home')renderHome();if(s.view==='explore')renderExplore();if(s.view==='night')renderNight();if(s.view==='saved')renderSaved();if(s.view==='plan')renderPlan();updateConnection();hydrateImages();}
function updateConnection(){const stamp=s.stats?.last_seen_at||s.rows.map(a=>a.last_seen_at).filter(Boolean).sort().at(-1);$('connectionText').textContent=s.mode==='live'?`${s.rows.length} פריטים להצגה · מאגר מחובר${stamp?' · '+dlabel(stamp):''}`:s.mode==='cache'?`${s.rows.length} פריטים מגיבוי מקומי · אין חיבור חי`:s.mode==='error'?'החיבור למאגר לא זמין כרגע':'מתחבר למאגר הארצי…';}
function cities(region,current=''){const all=[...new Set(s.rows.filter(a=>region==='all'||a.region===region).map(a=>a.city).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'he'));$('cityInput').innerHTML='<option value="">כל הערים באזור</option>'+all.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('cityInput').value=all.includes(current)?current:'';}
function openFilters(mode='search'){closeDialogs();s.formMode=mode;const f=s.filters;$('filterTitle').textContent=mode==='plan'?'מרכיבים תוכנית':'מה מחפשים?';$('applyFilters').textContent=mode==='plan'?'הרכבת תוכנית ✦':'הצגת תוצאות';$('moodInput').value=f.mood;$('regionInput').value=f.region;cities(f.region,f.city);$('fromInput').value=f.from;$('toInput').value=f.to;$('ageInput').value=f.age??'';$('budgetInput').value=f.budget??'';$('knownInput').checked=f.known;$('filterError').textContent='';$('filterDialog').showModal();}
function persistSaved(){if(!write('mta_v8_saved',[...s.saved]))toast('הדפדפן לא מאפשר שמירה קבועה. השמירה זמינה רק עד סגירת העמוד.');}
function toggleSaved(id){s.saved.has(id)?s.saved.delete(id):s.saved.add(id);persistSaved();document.querySelectorAll('[data-save]').forEach(b=>{const saved=s.saved.has(b.dataset.save);b.setAttribute('aria-pressed',String(saved));b.textContent=b.classList.contains('save-btn')?(saved?'♥':'♡'):(saved?'♥ נשמר':'♡ שמירה');});if(s.view==='saved')renderSaved();toast(s.saved.has(id)?'נוסף לשמורים':'הוסר מהשמורים');}
function details(id){const a=s.byId.get(id);if(!a)return;s.detailId=id;closeDialogs();const age=a.min_age!==null?`${a.min_age}+${a.max_age!==null?' עד '+a.max_age:''}`:a.max_age!==null?'עד גיל '+a.max_age:txt(a.age_text)||'לא פורסם';const when=a.timeUnclear?'יש אי־בהירות בשעות במקור; בדקו אצל הספק':dateLabel(a);const maps=a.city&&a.venue?'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(a.venue+' '+a.city):'';$('detailContent').innerHTML=image(a,'detail-media')+`<div class="detail-body"><div class="eyebrow">${esc(kindLabel(a))}</div><h2>${esc(a.title)}</h2><p>${esc(a.description||'פרטים מלאים זמינים באתר הספק.')}</p><div class="fact-grid"><div class="fact"><small>מחיר בסיס שפורסם</small><strong>${esc(priceLabel(a))}</strong></div><div class="fact"><small>גיל כניסה</small><strong>${esc(age)}</strong></div><div class="fact"><small>מקום</small><strong>${esc([a.venue,a.city||a.region].filter(Boolean).join(' · '))}</strong></div><div class="fact"><small>מועד</small><strong>${esc(when)}</strong></div>${a.music_style?`<div class="fact"><small>סגנון מוזיקה</small><strong>${esc(txt(a.music_style))}</strong></div>`:''}</div><p class="footnote">המחיר עשוי להתייחס לאדם, זוג, חדר או חבילה. הוא אינו הצעת מחיר לכל המשתתפים. זמינות, תנאי כניסה ומחיר סופי יש לאמת לפני הזמנה.</p><div class="detail-actions"><a class="primary" href="${esc(a.booking_url)}" target="_blank" rel="noopener noreferrer">לאימות מחיר ולהזמנה ↗</a><button class="secondary" data-save="${esc(a.id)}" aria-pressed="${s.saved.has(a.id)}">${s.saved.has(a.id)?'♥ נשמר':'♡ שמירה'}</button>${maps?`<a class="secondary" href="${esc(maps)}" target="_blank" rel="noopener noreferrer">חיפוש במפה ↗</a>`:''}</div><p class="footnote">מקור: <a href="${esc(a.source_url||a.booking_url)}" target="_blank" rel="noopener noreferrer">${esc(a.source_name||host(a.booking_url))}</a>${a.last_seen_at?' · נקלט במאגר: '+esc(dlabel(a.last_seen_at)):''}</p></div>`;$('detailDialog').showModal();hydrateImages();}
function buildPlan(){const f={...s.filters};let pool=results();const counts=new Map();for(const a of pool)if(a.city)counts.set(a.city,(counts.get(a.city)||0)+1);const city=f.city||[...counts].sort((a,b)=>b[1]-a[1])[0]?.[0];if(!city){s.plan={city:'',filters:f,stops:[],reason:'לא נמצאו מספיק פריטים עם עיר מוגדרת. בחרו עיר יעד או הרחיבו את התאריכים.'};savePlan();view('plan');return;}pool=pool.filter(a=>a.city===city);const stops=[],used=new Set();let spent=0,hotelUsed=false;const n=Math.min(7,Math.round((Date.parse(f.to)-Date.parse(f.from))/86400000)+1);for(let i=0;i<n;i++){const d=plus(f.from,i);let fixed=0;for(const a of pool){if(stops.length>=12)break;const identity=(a.venue||a.title).toLowerCase();if(used.has(identity)||!a.starts_at||a.kind==='hotel'||a.timeUnclear||day(a.starts_at)!==d||fixed>=1)continue;if(f.budget!==null&&(a.currency!=='ILS'&&a.price_from!==null||a.price_from!==null&&spent+a.price_from>f.budget))continue;stops.push({id:a.id,day:d,flex:false});used.add(identity);if(a.price_from!==null&&a.currency==='ILS')spent+=a.price_from;fixed++;}
 for(const a of pool){if(stops.length>=12||stops.filter(x=>x.day===d).length>=3)break;const identity=(a.venue||a.title).toLowerCase();if(used.has(identity)||a.starts_at&&a.kind!=='hotel'||a.kind==='hotel'&&hotelUsed||a.kind==='hotel'&&!inRange(a,{...f,from:d,to:d}))continue;if(f.budget!==null&&(a.currency!=='ILS'&&a.price_from!==null||a.price_from!==null&&spent+a.price_from>f.budget))continue;stops.push({id:a.id,day:d,flex:true});used.add(identity);if(a.kind==='hotel')hotelUsed=true;if(a.price_from!==null&&a.currency==='ILS')spent+=a.price_from;}
 }s.plan={city,filters:f,stops,created:new Date().toISOString(),reason:stops.length?'':'לא נמצאו שילובים מספקים עם מועד ועיר ידועים.'};savePlan();view('plan');}
function savePlan(){if(!write('mta_v8_plan',s.plan))toast('התוכנית זמינה בעמוד זה בלבד; השמירה בדפדפן חסומה.');}
function renderPlan(){const p=s.plan;if(!p||!p.stops?.length){$('planContent').innerHTML=empty('התוכנית מתחילה כאן',p?.reason||'בחרו תאריכים, עיר וסגנון. נרכז הצעות באותה עיר, בלי להמציא שעות או זמינות.','planner');return;}const available=p.stops.filter(x=>s.byId.has(x.id));const unknown=available.filter(x=>s.byId.get(x.id).price_from===null||s.byId.get(x.id).currency!=='ILS').length;const total=available.reduce((t,x)=>{const a=s.byId.get(x.id);return t+(a.currency==='ILS'?(a.price_from??0):0);},0);let content=`<div class="plan-info"><h2>${esc(p.city)}</h2><p>${esc(dlabel(at(p.filters.from))+' – '+dlabel(at(p.filters.to)))} · ${available.length} הצעות</p><strong>סכום מחירי בסיס ידועים: ${esc(currency(total))}</strong><p>${unknown?`${unknown} הצעות ללא מחיר שקלי ידוע. `:''}זה אינו מחיר כולל לתוכנית: יחידות המחיר ומספר המשתתפים עדיין טעונים אימות.</p><p>פעילויות גמישות מוצעות ללא שעה. בדקו זמינות, משך פעילות וזמן נסיעה אצל הספקים לפני היציאה.</p>${available.length!==p.stops.length?'<p>חלק מההצעות כבר אינן פעילות ולכן הוסתרו.</p>':''}</div>`;let prev='';available.forEach((x,i)=>{const a=s.byId.get(x.id);if(x.day!==prev){content+=`<h3 class="day-title">${esc(dlabel(at(x.day)))}</h3>`;prev=x.day;}content+=`<article class="plan-stop"><span class="stop-marker">${i+1}</span><div class="stop-body"><h3>${esc(a.title)}</h3><p>${esc(x.flex?'פעילות גמישה — יש לתאם מועד':clock(a.starts_at)+' · שעת התחלה לפי המקור')}</p><p>${esc(priceLabel(a))}</p><div class="stop-actions"><button data-detail="${esc(a.id)}">פרטים והזמנה ↗</button><button data-remove="${esc(a.id)}">הסרה</button></div></div></article>`;});$('planContent').innerHTML=content;}
async function sharePlan(){const p=s.plan;if(!p?.stops?.length){toast('צריך לבנות תוכנית לפני השיתוף');return;}const text=['התוכנית שלי · Mood Travel AI',p.city,...p.stops.map(x=>{const a=s.byId.get(x.id);return a?`${dlabel(at(x.day))} · ${a.title} · ${priceLabel(a)}\n${a.booking_url}`:''}).filter(Boolean),'יש לאמת מועדים, מחירים וזמינות אצל הספקים.'].join('\n\n');try{if(navigator.share){await navigator.share({title:'התוכנית שלי',text});return;}if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);toast('התוכנית הועתקה');return;}}catch(e){if(e.name==='AbortError')return;}const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='Mood-Travel-Plan.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function request(path){const ac=new AbortController(),t=setTimeout(()=>ac.abort(),12000);try{const r=await fetch(URL_BASE+path,{headers:{apikey:PUBLIC_KEY,Accept:'application/json'},signal:ac.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json();}finally{clearTimeout(t);}}
async function load(){if(s.loading)return;s.loading=true;const old=s.rows;updateConnection();const statPromise=request('/rest/v1/rpc/mt_catalog_status').then(v=>s.stats=v).catch(()=>{});try{let raw=[];const fields='id,title,description,type,category,moods,region,city,venue,starts_at,ends_at,min_age,max_age,price_from,currency,booking_url,source_url,image_url,is_free,source_name,last_seen_at,music_style,age_text';for(let offset=0;offset<5000;offset+=200){const batch=await request('/rest/v1/mt_activities?select='+encodeURIComponent(fields)+'&is_active=eq.true&order=id.asc&limit=200&offset='+offset);if(!Array.isArray(batch))throw new Error('Invalid catalog');raw.push(...batch);if(batch.length<200)break;}s.rows=normalize(raw);s.hidden=raw.length-s.rows.length;s.byId=new Map(s.rows.map(a=>[a.id,a]));s.mode='live';write('mta_v8_cache',{at:new Date().toISOString(),raw});}catch(e){const c=read('mta_v8_cache',null);if(c?.raw&&Array.isArray(c.raw)){s.rows=normalize(c.raw);s.byId=new Map(s.rows.map(a=>[a.id,a]));s.mode='cache';}else{s.rows=old;s.mode=old.length?'cache':'error';}console.warn('Mood catalog not reachable');}finally{await statPromise;s.loading=false;render();if($('statusDialog').open)renderStatus();}}
function renderStatus(){const run=s.stats?.last_run;const status=run?.status==='completed'?'הסריקה האחרונה הושלמה':run?.status==='completed_with_errors'?'הסריקה האחרונה הושלמה חלקית':run?.status==='running'?'הסריקה פועלת':run?.status==='failed'?'הסריקה האחרונה נכשלה':'אין פרטי סריקה זמינים';$('statusContent').innerHTML=`<div class="health-box"><strong>${s.mode==='live'?'המאגר מחובר':s.mode==='cache'?'מוצג גיבוי מקומי':'אין חיבור מאומת'}</strong><p>${s.rows.length} פריטים אחרי סינון אירועים שפגו, כפילויות וכותרות לא תקינות.</p>${s.stats?`<p>${Number(s.stats.sources)||0} מקורות מוגדרים · ${status}</p><p>${run?.finished_at?'סיום: '+esc(dlabel(run.finished_at)+' '+clock(run.finished_at)):''}${run?.errors_count?' · '+Number(run.errors_count)+' מקורות עם שגיאה':''}</p>`:''}<p>העדכון מתוזמן מדי יום. מקור חסום או מידע חסר אינם הוכחת זמינות. מחיר, גיל ושעות סופיים נבדקים אצל הספק.</p></div><p class="footnote">השמורים והתוכנית נשמרים בדפדפן במכשיר הזה; אין עדיין סנכרון אישי בין מכשירים. לא נשלחת בקשת הזמנה אוטומטית. V8</p>`;}
function action(name){if(name==='menu'){closeDialogs();$('menuDialog').showModal();}if(name==='status'){closeDialogs();renderStatus();$('statusDialog').showModal();}if(name==='filters')openFilters();if(name==='planner')openFilters('plan');if(name==='refresh'){toast('מרענן מהמאגר…');load();}if(name==='more'){s.limit+=18;renderExplore();}if(name==='share-plan')sharePlan();if(name==='reset-filters'){s.filters=defaults();openFilters(s.formMode);}}
$('brandImage').src=A.logo;$('heroImage').src=A.romantic;
$('moodTiles').innerHTML=['romantic','party','music','nature','family','food','hotel','spa'].map(k=>`<button class="mood-tile" data-mood="${k}"><div class="tile-img"><img src="${A[CATS[k][2]]}" alt="תמונת אווירה — ${CATS[k][0]}" loading="lazy"><span>${CATS[k][1]}</span></div>${CATS[k][0]}</button>`).join('');
$('moodInput').innerHTML=Object.entries(CATS).map(([k,v])=>`<option value="${k}">${v[0]}</option>`).join('');
$('nightDate').value=+clock(new Date()).split(':')[0]<6?plus(day(),-1):day();
$('nightChips').innerHTML=['all','party','clubs','music','bars'].map(k=>`<button class="chip ${k==='all'?'active':''}" data-night="${k}">${CATS[k][0]}</button>`).join('');
document.addEventListener('error',e=>{const im=e.target;if(!(im instanceof HTMLImageElement)||!im.dataset.fallback||im.dataset.illustration)return;im.dataset.illustration='1';im.src=A[im.dataset.fallback]||A.romantic;im.alt='תמונת אווירה';const note=im.parentElement.querySelector('.image-note');if(note)note.textContent='תמונת אווירה';},true);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close')){b.closest('dialog')?.close();return;}if(b.dataset.view){view(b.dataset.view);return;}if(b.dataset.action){action(b.dataset.action);return;}if(b.dataset.save){toggleSaved(b.dataset.save);return;}if(b.dataset.detail){details(b.dataset.detail);return;}if(b.dataset.mood){s.filters.mood=b.dataset.mood;$('heroImage').src=A[CATS[b.dataset.mood][2]];s.limit=18;view('explore');return;}if(b.dataset.night){s.nightKind=b.dataset.night;document.querySelectorAll('[data-night]').forEach(x=>x.classList.toggle('active',x===b));renderNight();return;}if(b.dataset.remove){s.plan.stops=s.plan.stops.filter(x=>x.id!==b.dataset.remove);savePlan();renderPlan();}});
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
$('filterForm').addEventListener('submit',e=>{e.preventDefault();const f={mood:$('moodInput').value,region:$('regionInput').value,city:$('cityInput').value,from:$('fromInput').value,to:$('toInput').value,age:num($('ageInput').value),budget:num($('budgetInput').value),known:$('knownInput').checked};if(!f.from||!f.to||f.to<f.from){$('filterError').textContent='תאריך הסיום חייב להיות אחרי תאריך ההתחלה או באותו היום.';return;}if(s.formMode==='plan'&&Date.parse(f.to)-Date.parse(f.from)>6*86400000){$('filterError').textContent='בתכנון אחד אפשר לבחור עד 7 ימים.';return;}s.filters=f;s.limit=18;$('heroImage').src=A[CATS[f.mood][2]];closeDialogs();if(s.formMode==='plan')buildPlan();else view(s.view==='night'?'night':'explore');});
$('regionInput').addEventListener('change',()=>cities($('regionInput').value));
let searchTimer;$('searchInput').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{s.query=$('searchInput').value.trim();s.limit=18;renderExplore();},150);});
$('sortInput').addEventListener('change',()=>{s.sort=$('sortInput').value;renderExplore();});$('nightDate').addEventListener('change',renderNight);
window.addEventListener('popstate',()=>view(location.hash.slice(1)||'home',false));
view(['home','explore','night','plan','saved'].includes(location.hash.slice(1))?location.hash.slice(1):'home',false);load();
})();
