import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));
const change=(src,before,after)=>{if(!src.includes(before))throw new Error('V9 anchor not found: '+before.slice(0,90));return src.replace(before,after);};
export async function upgrade(template,css,js,assets){
 assets.logo=(await Promise.all([1,2,3,4,5,6].map(n=>fs.readFile(path.join(dir,'logo-v9-'+n+'.txt'),'utf8')))).join('').trim();
 if(!/^data:image\/webp;base64,[a-zA-Z0-9+/=]+$/.test(assets.logo))throw new Error('Invalid selected couple logo');
 css=await fs.readFile(path.join(dir,'style-v9.css'),'utf8');
 template=template.replace('content="#10192c"','content="#f7faff"').replace('content="8.0.0"','content="9.0.0"').replace('Mood Travel AI | V8','Mood Travel AI | בילויים זוגיים');
 template=template.replace('בילויים, הופעות וחופשות לפי הסגנון שלכם. חיפוש ארצי, תוכנית אישית וקישורים לספקים.','בילויים ופעילויות לזוגות בכל הארץ. דייטים, מסיבות, הופעות, טיולים, ספא וחופשות לשניים.');
 template=change(template,'<img id="brandImage" alt="Mood Travel AI">','<span class="brand-word" dir="ltr">Mood<span>Travel</span> <b>AI</b></span>');
 template=change(template,'<section class="view" id="view-home">','<section class="view" id="view-home">\n <div class="couple-masthead"><div class="logo-halo"></div><img id="homeLogo" alt="Mood Travel AI — חוויות לשניים" fetchpriority="high"><div class="couple-signature"><span>♡</span> חוויות משותפות. זיכרונות שלכם.</div></div>');
 template=change(template,'YOUR MOOD. YOUR NEXT ADVENTURE.','JUST THE TWO OF YOU');
 template=change(template,'פחות לחפש.<br><span>יותר לחוות.</span>','הזמן שלכם.<br><span>ביחד.</span>');
 template=change(template,'ערב ספונטני, יום בטבע או חופשה לשניים.<br>בוחרים מה בא לכם — ומתחילים לגלות.','דייט רומנטי, הופעה או לילה של ריקודים.<br>מוצאים את הבילוי שמתאים לשניכם.');
 template=change(template,'בואו נבנה תוכנית <span>✦</span>','בנו לנו בילוי זוגי <span>♡</span>');
 template=change(template,'לכל מצב רוח, חוויה','איך בא לכם לבלות יחד?');
 template=change(template,'מה מתאים לכם?','שני אנשים. הרבה אפשרויות.');
 template=change(template,'חיפוש מקום, הופעה או חוויה','חפשו את הדייט הבא שלכם');
 template=change(template,'לגלות משהו חדש','רעיונות לזמן שלכם');
 template=change(template,'בוחרים ויוצאים','מגלים ביחד');
 template=change(template,'הלילה עוד צעיר.','יוצאים יחד הלילה.');
 template=change(template,'מסיבות, מועדונים והופעות</p>','רוקדים, שרים ומבלים — בשניים</p>');
 template=change(template,'פרטי הפעילויות מגיעים ממאגר מקורות. זמינות ומחיר סופי נבדקים אצל הספק; תמונות אווירה אינן תמונות של המקום.','הרעיונות נבחרים לבילוי זוגי; לא כל פעילות היא חבילה זוגית של הספק. זמינות ומחיר לשניים נבדקים לפני הזמנה. תמונות אווירה מסומנות.');
 template=change(template,'מה עושים הפעם?','מה עושים ביחד?');
 template=change(template,'כל הארץ, הרבה סגנונות, בחירה אחת שלכם.','בילויים לזוגות בכל הארץ — מרגע שקט ועד לילה סוער.');
 template=change(template,'מה קורה הלילה?','הלילה שלכם');
 template=change(template,'אירועים מתוארכים בנפרד ממקומות שצריך לבדוק.','מוצאים בילוי לשניים. אירועים מתוארכים ומקומות להכיר מוצגים בנפרד.');
 template=change(template,'התוכנית שלכם','התוכנית הזוגית שלכם');
 template=change(template,'באותה עיר, לפי התאריכים וההעדפות.','לשני משתתפים, באותה עיר, לפי התאריכים וההעדפות שלכם.');
 template=change(template,'בניית תוכנית ✦','בניית בילוי זוגי ♡');
 template=change(template,'שווה לשמור','הדייטים ששמרתם');
 template=change(template,'כל מה שתפס לכם את העין. נשמר בדפדפן הזה.','כל מה שתרצו לעשות ביחד. נשמר בדפדפן הזה.');
 template=change(template,'<label>גיל<input id="ageInput" type="number" min="0" max="120" placeholder="לא חובה"></label>','<div class="couple-fixed full"><span>♡</span><div><strong>יוצאים בשניים</strong><small>החיפוש והתכנון מיועדים לזוג</small></div><b>2</b></div>\n  <label>הגיל שלך<input id="ageInput" type="number" min="0" max="120" placeholder="לא חובה"></label><label>גיל בן / בת הזוג<input id="partnerAgeInput" type="number" min="0" max="120" placeholder="לא חובה"></label>');
 template=change(template,'<label>תקציב ₪','<label class="full">תקציב לשניכם ₪');
 template=change(template,'רק הצעות עם מחיר שפורסם','רק הצעות עם מחיר לשניים שאפשר לחשב');
 template=change(template,'0 ₪ מציג רק פעילויות שסומנו כחינמיות. מחיר חסר אינו חינם. יחידת המחיר יכולה להיות אדם, זוג, חדר או חבילה.','0 ₪ מציג פעילויות חינמיות בלבד. מחיר לאדם מוכפל ב־2 רק כשהיחידה ברורה במקור. במחיר חסר או ביחידה לא ידועה, התאמה לתקציב אינה מאומתת. מלון מחייב בדיקת המחיר לכל הלילות.');
 template=template.replace('V8 · אתר ציבורי','V9 · לזוגות בלבד · אתר ציבורי');
 template=change(template,'<div class="menu-buttons">','<div class="audience-note">♡ מרומנטיקה ועד הרפתקה — כל המערכת מכוונת לבילוי זוגי.</div><div class="menu-buttons">');
 const glyph=(body)=>'<svg aria-hidden="true" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">'+body+'</svg>';
 const icons={home:glyph('<path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-7h6v7"/>'),search:glyph('<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>'),heart:glyph('<path d="M20.8 4.9a5.4 5.4 0 0 0-7.6 0L12 6.1l-1.2-1.2a5.4 5.4 0 1 0-7.6 7.6L12 21l8.8-8.5a5.4 5.4 0 0 0 0-7.6z"/>'),moon:glyph('<path d="M20.7 13.5A9 9 0 0 1 10.5 3.3a9 9 0 1 0 10.2 10.2z"/>'),plan:glyph('<rect x="4" y="5" width="16" height="16" rx="3"/><path d="M8 3v4m8-4v4M4 11h16m-11 5 2 2 4-4"/>'),menu:glyph('<path d="M4 6h16M4 12h12M4 18h16"/>'),refresh:glyph('<path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 7a7 7 0 0 1 12-1l2 6M4 12l2 6a7 7 0 0 0 12-1"/>')};
 template=template.replace('aria-label="פתיחת תפריט">☰','aria-label="פתיחת תפריט">'+icons.menu).replace('aria-label="מצב המאגר">↻','aria-label="מצב המאגר">'+icons.refresh);
 for(const [symbol,k] of [['⌂','home'],['⌕','search'],['☾','moon'],['✦','plan'],['♡','heart']])template=template.replace('<span>'+symbol+'</span>', '<span>'+icons[k]+'</span>');
 const cats="const CATS={all:['הכל לשניים','✦','romantic'],romantic:['דייט רומנטי','♡','romantic'],relax:['פשוט לנוח','☁','relax'],party:['לרקוד ביחד','◉','party'],clubs:['מועדונים','♫','party'],bars:['ברים','♧','food'],music:['הופעות','♪','music'],nature:['טיולים לשניים','↟','nature'],food:['קולינריה','♨','food'],hotel:['חופשה זוגית','▤','relax'],spa:['ספא לשניים','❋','relax'],culture:['תרבות','◇','music'],comedy:['סטנדאפ','☺','music'],extreme:['אקסטרים','↗','nature'],workshop:['סדנאות יחד','✧','food'],sports:['פעילות משותפת','◎','nature']};";
 js=js.replace(/const CATS=\{[^\n]+\};/,()=>cats);
 js=change(js,"to:plus(day(),7)","to:plus(day(),2)");
 js=change(js,"age:null,budget:null,known:false","age:null,partnerAge:null,budget:null,known:false");
 js=change(js,"plan:read('mta_v8_plan',null)","plan:read('mta_v9_plan',read('mta_v8_plan',null))");
 js=change(js,"write('mta_v8_plan',s.plan)","write('mta_v9_plan',s.plan)");
 js=change(js,"function normalize(input)",`${coupleHelpers}\nfunction normalize(input)`);
 js=change(js,"a.cat=category(a);","a.cat=category(a);if(/סדנ(?:ה|ת|אות)/.test(a.title))a.cat='workshop';");
 js=change(js,"const key=[a.title.toLowerCase()","if(!coupleEligible(a))continue;a.pair=pairPrice(a);\n const key=[a.title.toLowerCase()");
 js=change(js,"return out;}\nfunction imageKey", "return out.map(a=>({...a,pair:pairPrice(a)}));}\nfunction imageKey");
 const start=js.indexOf('function basic(a,f)'),end=js.indexOf('\nfunction inRange',start);
 if(start<0||end<0)throw new Error('basic filter not found');
 js=js.slice(0,start)+`function basic(a,f){if(f.region!=='all'&&a.region!==f.region)return false;if(f.city&&a.city!==f.city)return false;const ages=[f.age,f.partnerAge].filter(v=>v!==null&&v!==undefined);if(ages.some(v=>a.min_age!==null&&v<a.min_age||a.max_age!==null&&v>a.max_age))return false;const p=a.pair?.amount??null;if(f.known&&p===null)return false;if(f.budget===0&&!a.isFree)return false;if(f.budget!==null&&p!==null&&(a.currency!=='ILS'||p>f.budget))return false;return true;}`+js.slice(end);
 js=change(js,"const priceLabel=a=>a.isFree?'חינם':a.price_from===null?'מחיר לא פורסם':'מ־'+currency(a.price_from,a.currency);","const priceLabel=a=>a.isFree?'חינם לשניכם':a.pair?.amount!==null&&a.pair?.amount!==undefined?'מ־'+currency(a.pair.amount,a.currency)+' '+a.pair.label:a.price_from===null?'מחיר לשניים בבדיקה':'מ־'+currency(a.price_from,a.currency)+' · מחיר בסיס';");
 js=change(js,"s.sort==='price'?((a.currency==='ILS'?a.price_from:null)??Infinity)-((b.currency==='ILS'?b.price_from:null)??Infinity)","s.sort==='price'?((a.currency==='ILS'?a.pair?.amount:null)??Infinity)-((b.currency==='ILS'?b.pair?.amount:null)??Infinity)");
 js=change(js,"['party','music','hotel','nature','family','food','spa','culture']","['party','music','hotel','nature','food','spa','culture','workshop']");
 js=change(js,"$('brandImage').src=A.logo;","$('homeLogo').src=A.logo;");
 js=change(js,"['romantic','party','music','nature','family','food','hotel','spa']","['romantic','party','music','nature','food','hotel','spa','workshop']");
 js=change(js,"$('filterTitle').textContent=mode==='plan'?'מרכיבים תוכנית':'מה מחפשים?';","$('filterTitle').textContent=mode==='plan'?'מרכיבים בילוי לשניים':'מה בא לכם לעשות ביחד?';");
 js=change(js,"$('ageInput').value=f.age??'';","$('ageInput').value=f.age??'';$('partnerAgeInput').value=f.partnerAge??'';");
 js=change(js,"age:num($('ageInput').value),budget:","age:num($('ageInput').value),partnerAge:num($('partnerAgeInput').value),budget:");
 js=change(js,"מחיר בסיס שפורסם","מחיר לשניים / מחיר בסיס");
 js=change(js,"המחיר עשוי להתייחס לאדם, זוג, חדר או חבילה. הוא אינו הצעת מחיר לכל המשתתפים. זמינות, תנאי כניסה ומחיר סופי יש לאמת לפני הזמנה.","${esc(a.pair?.note||'מחיר לשניים אינו מפורט במקור. מחיר הבסיס אינו בהכרח המחיר לזוג.')} זמינות, תנאי כניסה ומחיר סופי לשני משתתפים יש לאמת לפני הזמנה. לינה: יש לבדוק את העלות לכל הלילות.");
 js=change(js,"<div class=\"eyebrow\">${esc(kindLabel(a))}</div>","<div class=\"eyebrow\">${esc(kindLabel(a))} · רעיון לבילוי משותף</div>");
 js=change(js,"if(s.formMode==='plan')buildPlan();","if(s.formMode==='plan')buildPlan();");
 // Use only calculable activity prices for two in a plan, never a generic base price.
 const bp=js.indexOf('function buildPlan()'),ep=js.indexOf('\nfunction savePlan()',bp);
 let fn=js.slice(bp,ep);
 fn=fn.replaceAll("a.currency!=='ILS'&&a.price_from!==null||a.price_from!==null&&spent+a.price_from>f.budget","a.currency!=='ILS'&&planCost(a)!==null||planCost(a)!==null&&spent+planCost(a)>f.budget");
 fn=fn.replaceAll("if(a.price_from!==null&&a.currency==='ILS')spent+=a.price_from;","if(planCost(a)!==null&&a.currency==='ILS')spent+=planCost(a);");
 js=js.slice(0,bp)+fn+js.slice(ep);
 js=change(js,"s.byId.get(x.id).price_from===null||s.byId.get(x.id).currency!=='ILS'","planCost(s.byId.get(x.id))===null||s.byId.get(x.id).currency!=='ILS'");
 js=change(js,"(a.price_from??0)","(planCost(a)??0)");
 js=change(js,"סכום מחירי בסיס ידועים:","עלות פעילויות מחושבת לשניים:");
 js=change(js,"הצעות ללא מחיר שקלי ידוע.","הצעות / לינה ללא עלות כוללת לשניים.");
 js=change(js,"זה אינו מחיר כולל לתוכנית: יחידות המחיר ומספר המשתתפים עדיין טעונים אימות.","זהו סכום חלקי לשני משתתפים, לא הצעת מחיר סופית. לינה ורכיבים שאין להם מחיר זוגי ברור אינם כלולים. יש לאמת מחיר וזמינות אצל הספק.");
 js=js.replace("לא נשלחת בקשת הזמנה אוטומטית. V8","לא נשלחת בקשת הזמנה אוטומטית. V9 · בילויים זוגיים");
 return {template,css,js,assets};
}
const coupleHelpers=String.raw`
function coupleEligible(a){
 const title=a.title||'',cat=a.category||'',desc=a.description||'';
 if(/^(?:ינואר|פברואר|מרץ|אפריל|מאי|יוני|יולי|אוגוסט|ספטמבר|אוקטובר|נובמבר|דצמבר)\s+20\d{2}$/.test(title))return false;
 if(/^(?:לכל ה|כל האירועים|מה קורה בעיר|אמנות ותרבות|דילים למהירי החלטה|מוסדות תרבות|קורסים וסדנאות|אירועים ומופעים|מבצעים והטבות)$/.test(title))return false;
 if(/^(?:לכל ה|כל האירועים)/.test(title))return false;
 if(/(?:הצג(?:ה|ת|ות) ילדים|מופעי? ילדים|מופע לילדים|לפעוטות|לקטנטנים|לגיל הרך|ג[׳']?ימבורי|קייטנ|דיגיטף|סדנ(?:ה|ת|אות) לילדים)/.test(title))return false;
 if(/ילדים|למשפחה|משפחות|פארק שעשועים|מוזיאון ומדע|אקווריום/.test(cat))return false;
 if(/ספארי|לונה פארק|סופרלנד|מדעטק|גן החיות|אקווריום ישראל/.test(title))return false;
 if(a.max_age!==null&&a.max_age<18)return false;
 if(a.cat==='family'||a.cat==='kids')return false;
 if(/(?:פעילות|אירוע) (?:למשפחות|לילדים)|מתאים לילדים בלבד/.test(desc.slice(0,180)))return false;
 return true;
}
function pairPrice(a){
 if(a.isFree)return {amount:0,label:'לשניכם',note:'הפעילות סומנה כחינמית במקור.'};
 const p=a.price_from;
 if(p===null)return {amount:null,label:'',note:'אין מחיר שמאפשר חישוב לשניים.'};
 const text=(a.description||a.title).replace(/,/g,'');
 const values=[...text.matchAll(/(?:₪\s*(\d+(?:\.\d+)?)|(\d+(?:\.\d+)?)\s*(?:₪|ש[״"]?ח))/g)].map(m=>+((m[1]||m[2])));
 const nums=[...new Set(values)];
 if(nums.length!==1||nums[0]!==p)return {amount:null,label:'',note:'יחידת מחיר הבסיס אינה חד־משמעית; צריך לבדוק מחיר לשניים.'};
 const pair=/לזוג|לשניים|לשני משתתפים|per couple/i.test(text),person=/לאדם|למבוגר|לכרטיס|per person|per adult/i.test(text);
 if(pair&&!person)return {amount:p,label:/ללילה|per night/i.test(text)?'לזוג ללילה':'לזוג',note:'המקור מתאר את המחיר לזוג; תנאי החבילה והמחיר הסופי כפופים לספק.'};
 if(person&&!pair)return {amount:p*2,label:'לשניים',note:'חישוב לשניים: 2 × '+currency(p,a.currency)+' לפי מחיר לאדם שצוין במקור. אין בכך אישור לזמינות שני כרטיסים.'};
 return {amount:null,label:'',note:'המחיר שפורסם הוא מחיר בסיס; עלות לשניים אינה מאומתת.'};
}
function planCost(a){return a&&a.kind!=='hotel'?(a.pair?.amount??null):null;}
`;
