package com.tanziaisystems.floatcalc;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;

public class FloatingCalculatorService extends Service {
 private WindowManager wm; private View bubble,panel; private WindowManager.LayoutParams bp,pp; private TextView display,history; private String expr=""; private final ArrayList<String> hist=new ArrayList<>(); private static final String CH="floatcalc";
 @Override public void onCreate(){super.onCreate(); startForeground(77,notification()); wm=(WindowManager)getSystemService(WINDOW_SERVICE); showBubble();}
 @Override public int onStartCommand(Intent i,int f,int id){return START_STICKY;} @Override public android.os.IBinder onBind(Intent i){return null;}
 private Notification notification(){ if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CH,"TANZI FloatCalc",NotificationManager.IMPORTANCE_LOW);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);} Intent in=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,in,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT); Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CH):new Notification.Builder(this); return b.setSmallIcon(android.R.drawable.ic_dialog_dialer).setContentTitle("TANZI FloatCalc פעיל").setContentText("המחשבון הצף זמין על המסך").setOngoing(true).setContentIntent(pi).build(); }
 private GradientDrawable bg(int color,float radius,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(radius);if(stroke>0)g.setStroke(stroke,Color.rgb(53,221,255));return g;}
 private TextView tv(String t,int sz,int color){TextView v=new TextView(this);v.setText(t);v.setTextSize(sz);v.setTextColor(color);v.setGravity(Gravity.CENTER);return v;}
 private WindowManager.LayoutParams params(int w,int h){int type=Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE;return new WindowManager.LayoutParams(w,h,type,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,PixelFormat.TRANSLUCENT);}
 private void showBubble(){ if(bubble!=null)return; TextView b=tv("123",18,Color.WHITE);b.setTypeface(null,1);b.setBackground(bg(Color.rgb(20,24,38),80,4));bubble=b;bp=params(150,150);bp.gravity=Gravity.TOP|Gravity.START;bp.x=24;bp.y=300; final int[] d=new int[4];b.setOnTouchListener((v,e)->{if(e.getAction()==0){d[0]=(int)e.getRawX();d[1]=(int)e.getRawY();d[2]=bp.x;d[3]=bp.y;return true;}if(e.getAction()==2){bp.x=d[2]+(int)e.getRawX()-d[0];bp.y=d[3]+(int)e.getRawY()-d[1];wm.updateViewLayout(bubble,bp);return true;}if(e.getAction()==1){if(Math.abs(e.getRawX()-d[0])<20&&Math.abs(e.getRawY()-d[1])<20)openPanel();return true;}return false;});wm.addView(bubble,bp);}
 private Button key(String s){Button b=new Button(this);b.setText(s);b.setTextSize(20);b.setTextColor(Color.WHITE);b.setAllCaps(false);int c=(s.equals("=")?Color.rgb(16,150,180):(s.matches("[+−×÷%()]")?Color.rgb(70,35,95):Color.rgb(28,31,45)));b.setBackground(bg(c,28,1));b.setOnClickListener(v->press(s));return b;}
 private void openPanel(){ if(panel!=null)return; LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(16,16,16,16);root.setBackground(bg(Color.argb(245,10,13,22),36,3)); LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView drag=tv("TANZI FloatCalc",17,Color.rgb(80,230,255));drag.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);top.addView(drag,new LinearLayout.LayoutParams(0,70,1));Button mini=key("—");top.addView(mini,new LinearLayout.LayoutParams(80,70));Button close=key("×");top.addView(close,new LinearLayout.LayoutParams(80,70));root.addView(top);
 history=tv("",12,Color.LTGRAY);history.setGravity(Gravity.END);root.addView(history,new LinearLayout.LayoutParams(-1,60));display=tv("0",32,Color.WHITE);display.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);display.setPadding(12,0,12,0);root.addView(display,new LinearLayout.LayoutParams(-1,105));
 String[][] keys={{"C","(",")","÷"},{"7","8","9","×"},{"4","5","6","−"},{"1","2","3","+"},{"%","0",".","="}}; for(String[] row:keys){LinearLayout r=new LinearLayout(this);for(String s:row){LinearLayout.LayoutParams k=new LinearLayout.LayoutParams(0,105,1);k.setMargins(4,4,4,4);r.addView(key(s),k);}root.addView(r,new LinearLayout.LayoutParams(-1,113));}
 panel=root;pp=params(860,790);pp.gravity=Gravity.CENTER; final int[] d=new int[4];drag.setOnTouchListener((v,e)->{if(e.getAction()==0){d[0]=(int)e.getRawX();d[1]=(int)e.getRawY();d[2]=pp.x;d[3]=pp.y;return true;}if(e.getAction()==2){pp.gravity=Gravity.TOP|Gravity.START;pp.x=d[2]+(int)e.getRawX()-d[0];pp.y=d[3]+(int)e.getRawY()-d[1];wm.updateViewLayout(panel,pp);return true;}return false;}); mini.setOnClickListener(v->hidePanel());close.setOnClickListener(v->{hidePanel();stopSelf();});wm.addView(panel,pp);}
 private void press(String s){if(s.equals("C")){expr="";display.setText("0");return;}if(s.equals("=")){try{double val=new Parser(expr.replace("×","*").replace("÷","/").replace("−","-").replace("%","/100")).parse();String out=format(val);hist.add(expr+" = "+out);if(hist.size()>3)hist.remove(0);history.setText(String.join("   •   ",hist));expr=out;display.setText(out);}catch(Exception e){display.setText("Error");expr="";}return;}if(expr.length()<40){expr+=s;display.setText(expr);}}
 private String format(double d){if(Double.isNaN(d)||Double.isInfinite(d))return "Error";if(Math.abs(d-Math.rint(d))<1e-10)return Long.toString(Math.round(d));return String.format(Locale.US,"%.10f",d).replaceAll("0+$","").replaceAll("\\.$","");}
 private void hidePanel(){if(panel!=null){wm.removeView(panel);panel=null;}}
 @Override public void onDestroy(){hidePanel();if(bubble!=null){wm.removeView(bubble);bubble=null;}super.onDestroy();}
 static class Parser{final String s;int p=-1,ch;Parser(String s){this.s=s;}void next(){ch=(++p<s.length())?s.charAt(p):-1;}boolean eat(int c){while(ch==' ')next();if(ch==c){next();return true;}return false;}double parse(){next();double x=expr();if(p<s.length())throw new RuntimeException();return x;}double expr(){double x=term();for(;;){if(eat('+'))x+=term();else if(eat('-'))x-=term();else return x;}}double term(){double x=factor();for(;;){if(eat('*'))x*=factor();else if(eat('/'))x/=factor();else return x;}}double factor(){if(eat('+'))return factor();if(eat('-'))return-factor();double x;int st=p;if(eat('(')){x=expr();if(!eat(')'))throw new RuntimeException();}else if((ch>='0'&&ch<='9')||ch=='.'){while((ch>='0'&&ch<='9')||ch=='.')next();x=Double.parseDouble(s.substring(st,p));}else throw new RuntimeException();return x;}}
}
